version: 2
updates:

  # Project Dependencies.

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    commit-message:
        prefix: "Upgraded"
        prefix-development: "Upgraded"

  # NPM.

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    commit-message:
        prefix: "Upgraded"
        prefix-development: "Upgraded"

  # Project Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"
