name: visual

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  percy:
    name: "Visual Regression Testing"
    runs-on: ubuntu-latest
    steps:

      - name: "Checks out the repository."
        uses: "actions/checkout@v4"

      - name: "Sets up PHP with Composer."
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: "Install Composer dependencies with no dev option."
        run: |
          composer install --no-dev --no-interaction --prefer-dist --no-suggest --no-scripts
          composer dump-autoload --optimize --no-dev

      - name: "Setup NodeJS."
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "Install NodeJS dependencies"
        run: npm install

      - name: "Logs debug information."
        run: |
          node --version
          npm --version

      - name: "Build test site."
        run: |
          npm run wp-env start
          ./bin/setup.sh

      - name: "Run Percy Tests"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          npx percy snapshot ./tests/visual/snapshots.yml --base-url=http://localhost:8888
